name: Build Idris 2 for Windows x64
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc
      - name: Install MSYS2 Prerequisites
        shell: msys2 {0}
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S make mingw-w64-x86_64-gcc
      - name: Checkout Idris 2
        uses: actions/checkout@v3
        with:
          repository: idris-lang/Idris2
          path: './Idris2'
      - name: Build Idris
        shell: msys2 {0}
        run: |
          cd ./Idris2
          export SCHEME=$GITHUB_WORKSPACE/chez-scheme/scheme
          make bootstrap && make install
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
          with:
            name: idris2.exe
            path: ./Idris2/build/exec/idris2.exe